project:
  type: website
  output-dir: docs

website:
  title: "TraceNet"
  navbar:
    background: "#0d1117"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - href: https://tracenet.shinyapps.io/TraceNet/
        text: "TraceNet Shiny App ↗"
        
    right:
      - href: minutes.qmd
        text: Minutes of Meetings
      - icon: github
        href: https://github.com/MaxiChia/TraceNet

format:
  html:
    theme: [flatly, custom.scss]
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Show code"
    code-tools: false
    fontsize: 1rem
    page-layout: full
    mermaid:
      theme: neutral