source('global.R')
cat('--- incident_events short_name counts ---\n')
print(sort(table(incident_events$short_name), decreasing=TRUE))
cat('\n--- org_nodes (first 10) ---\n')
print(head(org_nodes, 10))
cat('\n--- org_edges (first 10) ---\n')
print(head(org_edges, 10))
cat('\n--- parties sample (first 5) ---\n')
print(head(incident_events$parties, 5))
